<function> ::= <parameters>? <expression>

<parameters> ::= <parameter> ("," <parameter>)* ":"

<parameter> ::= <IDENTIFIER>

<expression> ::= <add_sub>

<add_sub> ::= <mul_div_mod> <add_sub_op>*

<add_sub_op> ::= "+" <mul_div_mod> | "-" <mul_div_mod>

<mul_div_mod> ::= <unary> <mul_div_mod_op>*

<mul_div_mod_op> ::= "*" <unary> | "/" <unary> | "%" <unary>

<unary> ::= "-" <unary> | <exponent>

<exponent> ::= <primary> <exponent_tail>?

<exponent_tail> ::= "^" <unary>

<primary> ::= <range> | <dice> | <group> | <variable> | <CONSTANT>

<group> ::= "(" <expression> ")"

<variable> ::= "{" <IDENTIFIER> "}"

<range> ::= "[" <expression> ":" <expression> "]"

<dice> ::= <base_dice> <drop_clause>*

<base_dice> ::= <dice_count> <D_OPERATOR> <standard_faces> | <dice_count> <D_OPERATOR> <custom_faces>

<dice_count> ::= <CONSTANT> | <variable> | <group>

<standard_faces> ::= <CONSTANT> | <variable> | <group>

<custom_faces> ::= "[" <CONSTANT> ("," <CONSTANT>)* "]"

<drop_clause> ::= "drop" "lowest" <drop_expression>? | "drop" "highest" <drop_expression>?

<drop_expression> ::= <CONSTANT> | <variable> | <group>
