[workspace]
members = ["xdy", "tree-sitter-xdy"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Todd L Smith <todd@availlang.org>"]
description = "Complex RPG dice expression evaluator with histogram support."

[workspace.dependencies]
cc = "1.1.8"
criterion = { version = "0.5.1", features = ["html_reports"] }
pretty_assertions = "1.4.0"
proc-macro2 = "1.0.86"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.204", features = ["derive"] }
syn = "2.0.72"
tree-sitter = ">=0.22.6"
uuid = { version = "1.10.0", features = ["serde", "v4"] }
