dictionaries = []
words = [
    "allocator",
    "arity",
    "augend",
    "availlang",
    "benchmarking",
    "bitor",
    "canonicalize",
    "coalescer",
    "cse",
    "dep",
    "deref",
    "externs",
    "immediates",
    "initializer",
    "lexeme",
    "liveness",
    "memoize",
    "memoized",
    "mul",
    "optimizers",
    "pseudorandom",
    "reroll",
    "rpg",
    "serde",
    "subexpression",
    "subexpressions",
    "substate",
    "underflows",
    "unindexed",
    "unoptimized",
    "worklist",
    "xdy",
    "µ",
]
flag_words = []
ignore_paths = []
